project_id = "yudlciokearepqzvgzxx"

[functions.google-sheets]
verify_jwt = false

[functions.pencairan-save]
verify_jwt = false

[functions.pencairan-update]
verify_jwt = false

[functions.send-manual-wa-notifications]
verify_jwt = false

[functions.send-karir-notifications]
verify_jwt = false

[functions.send-kebijakan-notifications]
verify_jwt = false
