// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltloelzcnnbxlreropql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bG9lbHpjbm5ieGxyZXJvcHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Mjg1MzUsImV4cCI6MjA2MTUwNDUzNX0.336O6QCRC7zPefyIyd9CfYK7UBZlFtrf2gWkJncdE3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);