// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdbaywkepfkiiohhhval.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYmF5d2tlcGZraWlvaGhodmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTczNjIsImV4cCI6MjA3NTY5MzM2Mn0.tcq0fuDevUQu-G27l-uWlNjzrtzbed41qFmZXQOprxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});